MONGO_HOST: mongodb-{{ env }}.dcinema.online
Redis_Host: redis-{{ env }}.dcinema.online
Mysql_Host: mysql-{{ env }}.dcinema.online
Rabbitmq_Host: rabbitmq-{{ env }}.dcinema.online
Catalogue_host: catalogue.backend-alb-{{ env }}.dcinema.online
Payment_Host: payment.backend-alb-{{ env }}.dcinema.online
Cart_Host: cart.backend-alb{{ env }}.dcinema.online
User_Host: user.backend-alb-{{ env }}.dcinema.online
Ship_Host: shipping.backend-alb-{{ env }}.dcinema.online
