[local]
localhost ansible_connection=local

[mongo]
localhost

[mysql]
localhost

[redis]
localhost

[rabbitmq]
localhost

[cart]
localhost

[catalogue]
localhost

[user]
localhost

[shipping]
localhost

[payment]
localhost

[frontend]
localhost
