  - name: Install redis
    command: dnf install mysql-server -y
  
  - name: start the service
    service:
     name: mysqld
     state: started
     enabled: true
  
  - name: setup root password
    command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"
    