# here we have many common tasks whic are executed for other services also , so we can put them under common tasks/*.yml
# use import_task to get all common tasks executed

  # need to create a directory and download code
  # if directory present then delete and create againg and download
  - name: application setup
    import_role:
     name: common
     tasks_from: app-setup

  - name: nodejs setup
    import_role:
      name: common
      tasks_from: nodejs

  - name: systemd setup
    import_role:
      name: common
      tasks_from: systemd-setup

  - name: Copy mongo repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install mongo db client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present
  # load user data
  - name: check catalogue schema exist or not
    shell:  mongosh --host "{{ MONGO_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
    tags: 
    - mongo  
  
  - name: print catalogue_output
    debug:
      msg: "{{ catalogue_output }}"
    tags: 
    - mongo
    # to run this particular task we are using tags, use -t mongo at the end of command
  - name: Load products
    shell: mongosh --host {{ MONGO_HOST }} </app/db/master-data.js
    when: catalogue_output.stdout | int < 0
    #stdout is in double qoutes so we are converting it to int
    tags:
    - mongo

  - name: start and enable
    import_role:
      name: common
      tasks_from: restart 